apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kc-route
  namespace: ${NAMESPACE}
spec:
  host: kc-${NAMESPACE}.${CLUSTER_APPS_DOMAIN}
  to:
    kind: Service
    name: kc-service
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
